# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Varietal.find_or_create_by(name: 'Albariño')
Varietal.find_or_create_by(name: 'Aligoté')
Varietal.find_or_create_by(name: 'Barbaresco')
Varietal.find_or_create_by(name: 'Beaujolais')
Varietal.find_or_create_by(name: 'Cabernet Franc')
Varietal.find_or_create_by(name: 'Cabernet Sauvignon')
Varietal.find_or_create_by(name: 'Cava')
Varietal.find_or_create_by(name: 'Champagne')
Varietal.find_or_create_by(name: 'Chardonnay')
Varietal.find_or_create_by(name: 'Châteauneuf-du-Pape')
Varietal.find_or_create_by(name: 'Chenin Blanc')
Varietal.find_or_create_by(name: 'Chianti')
Varietal.find_or_create_by(name: 'Colombard')
Varietal.find_or_create_by(name: 'Dolcetto')
Varietal.find_or_create_by(name: 'Frascati')
Varietal.find_or_create_by(name: 'Gamay')
Varietal.find_or_create_by(name: 'Gattinara')
Varietal.find_or_create_by(name: 'Gewürztraminer')
Varietal.find_or_create_by(name: 'Grappa')
Varietal.find_or_create_by(name: 'Grenache')
Varietal.find_or_create_by(name: 'Liebfraumilch')
Varietal.find_or_create_by(name: 'Madeira')
Varietal.find_or_create_by(name: 'Malbec')
Varietal.find_or_create_by(name: 'Merlot')
Varietal.find_or_create_by(name: 'Moscato')
Varietal.find_or_create_by(name: 'Mourvedre')
Varietal.find_or_create_by(name: 'Muscat')
Varietal.find_or_create_by(name: 'Petite Sirah')
Varietal.find_or_create_by(name: 'Pinot Blanc')
Varietal.find_or_create_by(name: 'Pinot Gris/Grigio')
Varietal.find_or_create_by(name: 'Pinot Noir')
Varietal.find_or_create_by(name: 'Port')
Varietal.find_or_create_by(name: 'Riesling')
Varietal.find_or_create_by(name: 'Rose')
Varietal.find_or_create_by(name: 'Sangiovese')
Varietal.find_or_create_by(name: 'Sauterns')
Varietal.find_or_create_by(name: 'Sauvignon Blanc')
Varietal.find_or_create_by(name: 'Sherry')
Varietal.find_or_create_by(name: 'Verdicchio')
Varietal.find_or_create_by(name: 'Viognier')
Varietal.find_or_create_by(name: 'Zinfandel')




Region.find_or_create_by(name: 'Alsace')
Region.find_or_create_by(name: 'Argentina')
Region.find_or_create_by(name: 'Austria')
Region.find_or_create_by(name: 'Bordeaux')
Region.find_or_create_by(name: 'Burgundy')
Region.find_or_create_by(name: 'Champagne')
Region.find_or_create_by(name: 'Chile')
Region.find_or_create_by(name: 'Germany')
Region.find_or_create_by(name: 'Loire Valley')
Region.find_or_create_by(name: 'Napa Valley')
Region.find_or_create_by(name: 'New Zealand')
Region.find_or_create_by(name: 'Piedmont')
Region.find_or_create_by(name: 'Provence')
Region.find_or_create_by(name: 'Portugal')
Region.find_or_create_by(name: 'Rhone Valley')
Region.find_or_create_by(name: 'Sicily')
Region.find_or_create_by(name: 'Sonoma')
Region.find_or_create_by(name: 'South Africa')
Region.find_or_create_by(name: 'Spain')
Region.find_or_create_by(name: 'Tuscany')
Region.find_or_create_by(name: 'Washington')
Region.find_or_create_by(name: 'Willamette Valley')
Region.find_or_create_by(name: 'Italy')
Region.find_or_create_by(name: 'France')

